kind: App
name: store
owner: rahilkzi

modules:
  - name: wordpress
    source: wasmer/wordpress-playground
    config: wp-config.json

  - name: static
    source: wasmer/static-web-server
    mount: public
